# Generated by Django 5.2.1 on 2025-05-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='изображение')),
                ('price', models.FloatField(verbose_name='цена')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='вес')),
                ('calorific', models.FloatField(blank=True, help_text='измеряется в ккал', null=True, verbose_name='калорийность')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип товаров',
                'verbose_name_plural': 'типы товаров',
            },
        ),
        migrations.CreateModel(
            name='PromoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('short_description', models.TextField(verbose_name='краткое описание')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('products', models.ManyToManyField(related_name='menus', to='products.productmodel', verbose_name='товары')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, related_name='baskets', to='products.productmodel', verbose_name='корзина')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttypemodel', verbose_name=''),
        ),
        migrations.CreateModel(
            name='PromoConditionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='описание')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='products.promomodel', verbose_name='акция')),
            ],
            options={
                'verbose_name': 'условие акции',
                'verbose_name_plural': 'условия акции',
            },
        ),
    ]
