# Generated by Django 5.2.1 on 2025-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttypemodel', verbose_name='тип'),
        ),
    ]
