# Generated by Django 5.2.1 on 2025-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='baskets', to='products.productmodel', verbose_name='продукты'),
        ),
    ]
